### ISSUE TITLE
[decode] time sequence related bug(NULL ptr acess) in decode

### ISSUE THREAD

**Issue by zhangcong2019** [oneapi-src/oneVPL-intel-gpu#246] opened 2022-10-24 08:59 UTC
## System information
- CPU information(`cat /proc/cpuinfo | grep "model name" | uniq`):
"model name      : 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz"
- GPU information(`lspci -nn | grep -E 'VGA|isplay`):
"00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:9a49] (rev 01)"
- Display server if rendering to display(X or wayland):
"no display"

## Issue behavior
NULL ptr acess

### Describe the current behavior
**time sequence related bug:**
after `m_pSegmentDecoder[i]` deleted in 
https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp#L788

This line still try to access `m_pSegmentDecoder[i]`
https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_supplier.cpp#L218

There is no garantee that `mfxSchedulerCore::Close` has been executed in https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/scheduler/linux/src/mfx_scheduler_core.cpp#L97

### Describe the expected behavior
thread should closed before resource release.

## Debug information
- What's libva/libva-utils/gmmlib/media-driver/VPL runtime version?
2.14, 22.1.2, 22.3.1, 2022.2
- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`? 
"by-path  card0  renderD128"
- Could you attach dmesg log if it's GPU hang by `dmesg >dmesg.log 2>&1`?

- Could you provide vainfo log if possible by `vainfo -a >vainfo.log 2>&1`?

- Could you provide strace log if possible by `strace YOUR_CMD >strace.log 2>&1`?

- Could you provide libva trace log if possible? Run cmd `export LIBVA_TRACE=/tmp/libva_trace.log` first then execute the case.

- Do you want to contribute a PR? (yes/no):
no

**Comment by Jexu** [comment] 2022-11-08 02:04
Need null check before access to the ptr

**Comment by zhangcong2019** [comment] 2022-11-08 02:14
> Need null check before access to the ptr

Thanks for reply, null ptr checker can solve this issue in most cases
one corner case is access to `m_pSegmentDecoder[i]` right after ptr delete and before ptr set to null

**Comment by Jexu** [comment] 2022-11-08 02:38
Yeah, this may need a mutex for thread sync when accessing to same variable.

**Comment by zhangcong2019** [comment] 2022-11-08 03:04
> Yeah, this may need a mutex for thread sync when accessing to same variable.

agree

**Comment by intel-mediadev** [comment] 2023-04-03 06:50
Auto Created VSMGWL-63158 for further analysis.

**Comment by huangli2018** [comment] 2023-04-10 06:05
1. Sorry for delay reply. Checked VPL scheduler and thread logic, there won't  be  nullptr access for  m_pSegmentDecoder[i], as it waits for all task completion before resource release. https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/shared/src/libmfxsw_decode.cpp#L473 
MfxschedulerCore will setup several sub threads, then they will wait until get task.
the main thread  requests entrypoints by calling something like *FrameCheck, then it add task and wake up the sub thread to excute "RunThread function" to get driver status.
Before Resource release, it calls WaitforAllTaskCompletion function, in this function, it checks all task status(get from sub thread) and waits for all task done.
So before resource release, all sub thread execution should be done.

**Comment by zhangcong2019** [comment] 2023-04-17 05:47
> 1. Sorry for delay reply. Checked VPL scheduler and thread logic, there won't  be  nullptr access for  m_pSegmentDecoder[i], as it waits for all task completion before resource release. https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/shared/src/libmfxsw_decode.cpp#L473
> 2. MfxschedulerCore will setup several sub threads , then they will wait until get task.
>    3.The main thread  requests entrypoints by calling something like *FrameCheck, then it add task and wake up the sub thread to excute "RunThread function" to get driver status.
>    Before Resource release, it calls WaitforAllTaskCompletion function, in this function, it checks all task status(get from sub thread) and waits for all task done.
>    So before resource release, all sub thread execution should be done.

Thank you so much Li for the detailed explanation, looks you are right, "wait task completion" can avoid such issue happen.

But I did see such error in my test, and I don't have that environment now. I guess if there are some multi-thread corner cases that this "wait task completion" logic would fail? (for example a new task is created after or during "wait task completion", like `addTask` may happen during execution of this line https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/scheduler/linux/src/mfx_scheduler_core_ischeduler.cpp#L345)

Anyway, I believe in most cases this "wait task completion" logic should work fine, my concern is cleared, thanks again for your effort on investigation of this issue.

**Comment by huangli2018** [comment] 2023-05-09 03:06
> > 1. Sorry for delay reply. Checked VPL scheduler and thread logic, there won't  be  nullptr access for  m_pSegmentDecoder[i], as it waits for all task completion before resource release. https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/shared/src/libmfxsw_decode.cpp#L473
> > 2. MfxschedulerCore will setup several sub threads , then they will wait until get task.
> >    3.The main thread  requests entrypoints by calling something like *FrameCheck, then it add task and wake up the sub thread to excute "RunThread function" to get driver status.
> >    Before Resource release, it calls WaitforAllTaskCompletion function, in this function, it checks all task status(get from sub thread) and waits for all task done.
> >    So before resource release, all sub thread execution should be done.
> 
> Thank you so much Li for the detailed explanation, looks you are right, "wait task completion" can avoid such issue happen.
> 
> But I did see such error in my test, and I don't have that environment now. I guess if there are some multi-thread corner cases that this "wait task completion" logic would fail? (for example a new task is created after or during "wait task completion", like `addTask` may happen during execution of this line https://github.com/oneapi-src/oneVPL-intel-gpu/blob/main/_studio/mfx_lib/scheduler/linux/src/mfx_scheduler_core_ischeduler.cpp#L345)
> 
> Anyway, I believe in most cases this "wait task completion" logic should work fine, my concern is cleared, thanks again for your effort on investigation of this issue.

Hi @zhangcong2019 ,  For your concern "for example a new task is created after or during "wait task completion", like addTask may happen during execution of this line 345", it won't happen. Because "Task initialize""AddTask" and "WaitTaskCompletion" are all in main thread(function MFXVideoDECODE_DecodeFrameAsync()).
Back to the original NULL ptr access issue, as your concern is cleared. I will close this issue. If you still meet same issue, feel free to re-open it again. Thanks!

**Comment by Jexu** [comment] 2023-05-09 03:19
Thanks for agreement. If the explanation solves your concern, let me close it, you could open it again when still have any other questions.

**Closed by Jexu** 2023-05-09 03:19 UTC
Labels: bug, Decode

**Comment by zhangcong2019** [comment] 2023-05-09 06:44
@Jexu @huangli2018 , Let's close this first, when I reproduce this issue we can reopen it.
Anyway, thanks a lot for your support on this issue, really appreciate your effort and insights.
Please also forgive me for my obsession on this issue, I just want to clean potential bugs and make our product better.

**Comment by Jexu** [comment] 2023-05-10 01:57
Yeah, if you meet real issue about this, welcome to re-open it again and give the steps to reproduce it that will help analysis and debug it.
