### ISSUE TITLE
DG1: MFX_RATECONTROL_LA_HRD causes hang

### ISSUE THREAD

**Issue by gizahNL** [oneapi-src/oneVPL-intel-gpu#229] opened 2022-08-18 10:13 UTC
## System information
- model name	: AMD Ryzen 5 3600 6-Core Processor
- **26:00.0 VGA compatible controller [0300]: Intel Corporation DG1 [Iris Xe Graphics] [8086:4908] (rev 01)**  
     30:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Navi 22 [Radeon RX 6700/6700 XT / 6800M] [1002:73df] (rev c1)
- Wayland (irrelevant: DG1 GPU isn't used for Display & only accessed via /dev/dri/renderD# node)

### Describe the current behavior
When RateControlMethod is set to MFX_RATECONTROL_LA_HRD encoding will start and (eventually) return _(mfxExtCodingOption2.LookAheadDepth + mfxVideoParam.mfx.GopRefDist -1)_ frames, after which  MFXVideoCORE_SyncOperation(session, sync, 100) will return MFX_WRN_IN_EXECUTION 20 times and afterwards finally failing with MFX_ERR_GPU_HANG 
### Describe the expected behavior
There shouldn't be a hang.

## Debug information
- What's libva/libva-utils/gmmlib/media-driver/VPL runtime version?
```
dpkg -l | grep libva        
ii  libva-dev:amd64                            2.14.0-1                                amd64        Video Acceleration (VA) API for Linux -- development files
ii  libva-drm2:amd64                           2.14.0-1                                amd64        Video Acceleration (VA) API for Linux -- DRM runtime
ii  libva-glx2:amd64                           2.14.0-1                                amd64        Video Acceleration (VA) API for Linux -- GLX runtime
ii  libva-wayland2:amd64                       2.14.0-1                                amd64        Video Acceleration (VA) API for Linux -- Wayland runtime
ii  libva-x11-2:amd64                          2.14.0-1                                amd64        Video Acceleration (VA) API for Linux -- X11 runtime
ii  libva2:amd64                               2.14.0-1                                amd64        Video Acceleration (VA) API for Linux -- runtime
ii  libva2:i386                                2.14.0-1                                i386         Video Acceleration (VA) API for Linux -- runtime
ii  libvariable-magic-perl                     0.62-1build5                            amd64        module to associate user-defined magic to variables from Perl
```
```
gmmlib: intel-gmmlib-22.1.7,  f7194832aa1cb11d9ef4666afc6887178b378660 (from source)
media-driver: intel-media-22.5.2, 0b379d06743ad4baf229b6a2f2aaa3d4fb1b31ec (idem) (build with ENABLE_PRODUCTION_KMD=ON)
onevpl-runtime: intel-onevpl-22.5.2 65e81095b958b5a2111b5cb06818b8a7c94c7ea2 (idem)/

Kernel (parsing dmesg.txt attached below, essential parts):
[    0.000000] Linux version 5.17.0-1015-oem (buildd@lcy02-amd64-003) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #16-Ubuntu SMP PREEMPT Mon Aug 8 19:09:19 UTC 2022 (Ubuntu 5.17.0-1015.16-oem 5.17.15)

$ less dmesg.txt | grep -i backport
[   14.784599] COMPAT BACKPORTED INIT
[   14.784599] Loading modules backported from DII_5949_hotfix2
[   14.784600] Backport generated by backports.git UBUNTU_2204_OEM_5949_PRERELEASE_220707.2
[   14.942675] [drm] I915 BACKPORTED INIT
[   15.160758] [drm] I915 SPI BACKPORTED INIT
```

And dmesg part related to GPU hang:
```
[  944.111292] i915 0000:26:00.0: [drm] *ERROR* GPU catastrophic memory error. GT: 0, GuC context: 0x1007
[  955.841274] i915 0000:26:00.0: [drm] GPU HANG: ecode 12:1:00000000, in obecli [12259]
```

- Could you confirm whether GPU hardware exist or not by `ls /dev/dri`? **Exists**
[vainfo.txt](https://github.com/oneapi-src/oneVPL-intel-gpu/files/9372535/vainfo.txt)
[dmesg.txt](https://github.com/oneapi-src/oneVPL-intel-gpu/files/9372542/dmesg.txt)
[strace.log](https://github.com/oneapi-src/oneVPL-intel-gpu/files/9372553/strace.log)
[libva_trace_2.log](https://github.com/oneapi-src/oneVPL-intel-gpu/files/9372567/libva_trace_2.log)
[libva_trace_1.log](https://github.com/oneapi-src/oneVPL-intel-gpu/files/9372568/libva_trace_1.log)

**Comment by gizahNL** [comment] 2022-08-18 10:43
The hang seems to be caused by "draining" the encoder. 

Pseudo code causing the issue:
```
while true {
    FillFrameData();
    ret  = MFXVideoENCODE_EncodeFrameAsync(session, NULL, encSurfaceIn, &bitstream, &sync);
    if ret == MFX_ERR_MORE_DATA
      continue;
    else if ret == MFX_ERR_NONE {
      while (ret = MFX_ERR_NONE)
          MFXVideoCORE_SyncOperation(session, sync, 100);
          //validate sync op
          //use bitstream data
          ret = MFXVideoENCODE_EncodeFrameAsync(session, NULL, NULL, &bitstream, &sync);
    }
}
```
This does work on older HW (Intel Corporation UHD Graphics 620)

**Comment by dvrogozh** [comment] 2022-08-18 15:48
Just wondering. It seems you've installed DKMS kernel modules for i915 driver. Can you, please, point to the instruction which you've followed?

Have you tried to run sample_multi_transcode included into oneVPL? If you could reproduce the issue on it, that would be helpful.

**Comment by gizahNL** [comment] 2022-10-10 07:19
> Just wondering. It seems you've installed DKMS kernel modules for i915 driver. Can you, please, point to the instruction which you've followed?
> 
> Have you tried to run sample_multi_transcode included into oneVPL? If you could reproduce the issue on it, that would be helpful.

I used the official instructions associated with the repo published by Intel; And was running the matching Ubuntu OEM kernel.

Unfortunately I have upgraded my system since and am unable to setup the same configuration again.

**Comment by intel-mediadev** [comment] 2023-07-03 07:28
Auto Created VSMGWL-66144 for further analysis.

**Comment by OttoYang** [comment] 2023-07-04 02:05
> Unfortunately I have upgraded my system since and am unable to setup the same configuration again.  
Hi @gizahNL , can I assume you are unable to reproduce this issue on your device right now? And may I know which version your system was upgraded to? Thanks.

**Comment by gizahNL** [comment] 2023-07-05 15:42
> > Unfortunately I have upgraded my system since and am unable to setup the same configuration again.
> 
> Hi @gizahNL , can I assume you are unable to reproduce this issue on your device right now? And may I know which version your system was upgraded to? Thanks.

Currently running Ubuntu 23.04. 

I don't have the card in my system right now, which also doesn't help ;)

**Comment by OttoYang** [comment] 2023-07-13 01:45
Hi @gizahNL , I'll close this issue as none of us have env or tool to reproduce it.  
Thanks for your feedback and feel free to create an issue if you have any questions or problems with hw encoding.

**Closed** 2023-07-13 09:08 UTC
Labels: bug, AVC, Encode, Reserved
