### ISSUE TITLE
AV1Enc wrong timestamp when having b frames

### ISSUE THREAD

**Issue by mengker33** [oneapi-src/oneVPL-intel-gpu#206] opened 2022-04-01 03:48 UTC
### Describe the current behavior

When having b frame larger than 1, timestamps are incorrect in mfxBitstream, i.e. for some encoded frames, dts (mfxBitstream.DecodeTimeStamp) is larger than pts (mfxBitstream.TimeStamp).

### Describe the expected behavior
Pts and dts in mfxBitstream follow the correct rule as dts < pts when having b frame encoding.

**Comment by xuguangxin** [comment] 2022-04-02 05:38
@mengker33 please provide the reproduce steps. thanks

**Comment by mengker33** [comment] 2022-04-08 02:12
Please apply the **patch**, then run the cmd:
`sample_encode av1 -i input.yuv -w 1920 -h 1080 -i420 -r 3 -o output.av1 -n 10`
The print-info will show that e.g the 3rd frame and 4th frame, pts are smaller than dts.

**Comment by xuguangxin** [comment] 2022-04-08 03:35
@cchunbo , could assign the right people for this issue?

thanks

**Comment by MaximIntel** [comment] 2022-05-11 05:36
The issue is already fixed by commit: https://github.com/oneapi-src/oneVPL-intel-gpu/commit/cfe551debf4873fd86f0fe2eea38713eb87f5ffc

**Closed by MaximIntel** 2022-05-11 05:36 UTC
Labels: bug
